name: flow-dependabot-auto-merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    uses: igrek8/github-workflows/.github/workflows/job-dependabot-auto-merge.yml@main
