name: flow-push

on:
  push:
    branches: [main]

jobs:
  define-labels:
    uses: ./.github/workflows/job-define-labels.yml
  format:
    uses: ./.github/workflows/job-format.yml
  lint:
    uses: ./.github/workflows/job-lint.yml
  test:
    uses: ./.github/workflows/job-test.yml
  build:
    uses: ./.github/workflows/job-build.yml
  analyze:
    uses: ./.github/workflows/job-analyze.yml
  security:
    uses: ./.github/workflows/job-security.yml
  release:
    needs: [define-labels, format, lint, test, build, analyze, security]
    uses: ./.github/workflows/job-release.yml
  docs:
    needs: [release]
    uses: ./.github/workflows/job-docs.yml
