on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
      artifact-path:
        type: string
        required: false
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - if: ${{ inputs.artifact-name && inputs.artifact-path }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
