on: workflow_call

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage
      - name: coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
