on: workflow_call

jobs:
  dependabot-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review --approve "$PR_URL"
